auth:
  tokens:
    accessTokenExpiry: 3000
    refreshTokenExpiry: 6000
    refreshTokenRotationEnabled: true

  redirectUrl: http://localhost:8000/signedin

  providers:
    - type: oidc
      name: AuthZero
      issuerUrl: https://dev-skhlutl45lbqkvhv.us.auth0.com/
      clientId: 7hNx6BWSA5qofBClGUdMkbcF0dQqLKyY

    - type: google
      name: google
      clientId: 247884616520-22ts8a09i4qrdk64fq8jrgorcn08blf8.apps.googleusercontent.com

    - type: facebook
      name: fb
      clientId: 275725305447566

    - type: gitlab
      name: gitlab
      clientId: 18c6dcb0ac290380a8af740fcb5a665d676e104e603008cd609ad7920785f62d

secrets:
  - name: AUTH_PROVIDER_SECRET_GOOGLE
  - name: AUTH_PROVIDER_SECRET_AUTHZERO
  - name: AUTH_PROVIDER_SECRET_FB
  - name: AUTH_PROVIDER_SECRET_GITLAB